
package fr.afcepf.al34.serveur;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import fr.afcepf.al34.dto.ResCalculTva;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICalculTva", targetNamespace = "http://itf.al34.afcepf.fr/")
@XmlSeeAlso({
    fr.afcepf.al34.dto.ObjectFactory.class,
    fr.afcepf.al34.itf.ObjectFactory.class
})
public interface ICalculTva {


    /**
     * 
     * @param ht
     * @param tauxTva
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ttc", targetNamespace = "http://itf.al34.afcepf.fr/", className = "fr.afcepf.al34.itf.Ttc")
    @ResponseWrapper(localName = "ttcResponse", targetNamespace = "http://itf.al34.afcepf.fr/", className = "fr.afcepf.al34.itf.TtcResponse")
    public double ttc(
        @WebParam(name = "ht", targetNamespace = "")
        double ht,
        @WebParam(name = "tauxTva", targetNamespace = "")
        double tauxTva);

    /**
     * 
     * @param ht
     * @param tauxTva
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "tva", targetNamespace = "http://itf.al34.afcepf.fr/", className = "fr.afcepf.al34.itf.Tva")
    @ResponseWrapper(localName = "tvaResponse", targetNamespace = "http://itf.al34.afcepf.fr/", className = "fr.afcepf.al34.itf.TvaResponse")
    public double tva(
        @WebParam(name = "ht", targetNamespace = "")
        double ht,
        @WebParam(name = "tauxTva", targetNamespace = "")
        double tauxTva);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAuteur", targetNamespace = "http://itf.al34.afcepf.fr/", className = "fr.afcepf.al34.itf.GetAuteur")
    @ResponseWrapper(localName = "getAuteurResponse", targetNamespace = "http://itf.al34.afcepf.fr/", className = "fr.afcepf.al34.itf.GetAuteurResponse")
    public String getAuteur();

    /**
     * 
     * @param ht
     * @param tauxTva
     * @return
     *     returns fr.afcepf.al34.dto.ResCalculTva
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "tvaEtTtc", targetNamespace = "http://itf.al34.afcepf.fr/", className = "fr.afcepf.al34.itf.TvaEtTtc")
    @ResponseWrapper(localName = "tvaEtTtcResponse", targetNamespace = "http://itf.al34.afcepf.fr/", className = "fr.afcepf.al34.itf.TvaEtTtcResponse")
    public ResCalculTva tvaEtTtc(
        @WebParam(name = "ht", targetNamespace = "")
        double ht,
        @WebParam(name = "tauxTva", targetNamespace = "")
        double tauxTva);

}
